# Generated by Django 4.2.7 on 2023-12-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_answer_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='profile',
        ),
    ]
